### ISSUE TITLE
Create data transformation scripts for all forms of .olist files within the group's data. Needs to be tested on entirety of dataset.

### ISSUE THREAD

**Issue by joncwong** [joncwong/speckle-imaging#1]
For self-tracking issues within project.

**Comment by exlunae** [comment]
Script is currently able to transform olist files into a .txt file with space delimiters. 

To Do: 

Convert to .csv file with comma delimiters. 
Fix comments.

**Comment by exlunae** [comment]
> Script is currently able to transform olist files into a .txt file with space delimiters.
> 
> To Do:
> 
> Convert to .csv file with comma delimiters.
> Fix comments.

Olist file is able to be saved as .csv file now. Comments still need to be preserved and associated with the each entry.
